### ISSUE TITLE
tutorial_*.py 也需要更新

### ISSUE THREAD

**Issue by zsdonghao** [shorxp/tensorlayer-chinese#5]
帅哥，我电脑wechat掉线了，在公海上手机没法scan QR code了。。突然发现没有你的邮箱，有事Line或邮件联系。。

**Comment by shorxp** [comment]
什么情况.. 加我LINE: shorxp

**Comment by shorxp** [comment]
tutorial 的两个mnist py文件应该也已经更新了

**Comment by maxmo2009** [comment]
y.mo16@imperial.com

Thanks,
Yuanhan
------


2016-08-26 14:13 GMT+01:00 Xiaoping Fan <notifications@github.com>:
